language: cpp

sudo: required

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8

before_install:
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
    - chmod +x cxxtest-4.4/bin/cxxtestgen
            
script:
    - cd tests
    - make test