language: cpp

sudo: required

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8

before_install:
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
    - chmod +x cxxtest-4.4/bin/cxxtestgen
    - pip install --user cpp-coverall
            
script:
    - cd tests
    - make test
    
after_success:
  - coveralls --exclude include --exclude example --exclude cxxtest-4.4 --exclude tests --gcov-options '\-lp'
      
notifications:
  email:
    on_success: change
    on_failure: change